name: Continuous Integration and Security

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Use Node.js Version from Package.json
      run: npm ci

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install Dependencies and Run Tests
      run: npm install && npm test

    - name: Lint code with ESLint and fix errors
      run: |
        npm run lint -- --fix
        if [[ $? -ne 0 ]]; then
          exit 1
        fi

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: nodejs
        queries: security, best-practices, performance

    - name: Check for Security Vulnerabilities
      run: |
        npx bandit -q
        if [[ $? -ne 0 ]]; then
          exit 1
        fi

    - name: Format Code with Prettier
      run: npm run format

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: heroku-cli/heroku-deploy@v4
      with:
        app: your-heroku-app-name
        api_key: ${{ secrets.HEROKU_API_KEY }}
