name: Continuous Integration & Quality Assurance

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Cache Node.js dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci

    - name: Check for package.json format errors
      run: |
        npm fix --dry-run
        if [[ $? -ne 0 ]]; then
          echo "package.json format errors exist. Run `npm fix` to apply changes."
          exit 1
        fi

    - name: Run tests with coverage
      run: |
        npm test --coverage
        if [[ $? -ne 0 ]]; then
          echo "Test coverage threshold not met. Check the coverage report."
          exit 1
        fi
      
    - name: Lint code with ESLint
      run: |
        npm run lint --fix
        if [[ $? -ne 0 ]]; then
          echo "ESLint violations found. Fixing errors..."
          exit 1
        fi

    - name: Analyze security vulnerabilities with SonarQube
      uses: SonarSource/sonarqube-scanner-action@v2.3
      with:
        server_url: 'https://your-sonarqube-server.com'
        token: ${{ secrets.SONARQUBE_TOKEN }}
        organization: 'your-organization'
        additional_properties: |
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
          sonar.javascript.eslint.reportPaths=coverage/eslint.xml

    - name: Check for SmoothFlow compliance
      run: |
        npm run smoothflow
        if [[ $? -ne 0 ]]; then
          echo "SmoothFlow analysis failed. Check the report for errors."
          exit 1
        fi

    - name: Deploy to GitHub Pages (Optional)
      uses: actions/pages@v2
      with:
        destination: docs
        source: docs
